### PR TITLE
fix: middleware order #92

### PR DESCRIPTION
**Pull request by s-uei**

### CODE REVIEW

**Comment by crowlKats** [comment]
what does this fix?

**Comment by s-uei** [comment]
I want to fix the order of calling middlewares. Now it changes by loading page.
https://github.com/denoland/deno_blog/issues/92

**Comment by lino-levan** [comment]
LGTM! PTAL, @crowlKats.

**Review by LeoDog896 — APPROVED** [review]
LGTM! The only (minor) thing is that it was confusing at first when I looked at it -- would a spread operator be more clear to its intentions of cloning the array?

**Comment by s-uei** [comment]
> LGTM! Minor issue, but it may be me only: the `slice` call's intentions were a bit confusing at first -- would a spread operator be more clear to its intentions of cloning the array?

I agree but I cannot write good vibes code because `state.middlewares` maybe `undefined`.
```js
const mws = state.middlewares ? [...state.middlewares].reverse() : undefined
```

**Comment by LeoDog896** [comment]
Ah, makes sense, thanks for the clarification!

**Review by crowlKats — APPROVED** [review]
LGTM

**Pull request merged**
