### PR TITLE
feat: dark mode support

### PR DESCRIPTION
**Pull request by roj1512**

### CODE REVIEW

**Comment by roj1512** [comment]
@ije How should I modify the style of the dangerously set inner HTML of the blog content?

**Comment by ije** [comment]
we are using https://deno.land/x/gfm to crate blog content that supports dark mode i think

**Comment by roj1512** [comment]
@ije It's not working when I do `data-color-mode="auto"`

**Comment by roj1512** [comment]
@ije The `styles` parameter is broken in the latest `htm` :(

**Comment by ije** [comment]
@roj1512 nice job! just one thing, the text color of blog content has bad readability in dark mode, can you please change it lighter a bit? 
Screen Shot 2022-06-28 at 09 49 03

**Comment by roj1512** [comment]
@ije It is fine for me, are you running the correct file?

image

**Comment by ije** [comment]
@roj1512 I agree! the `background` option will break dark mode

**Review by ije — APPROVED** [review]
LGTM!

**Pull request merged**
