### PR TITLE
chore: update deps

### LINKED ISSUE #23: Lists are not styled
Both ordered and unordered lists look like this:

image

### PR DESCRIPTION
**Pull request by roj1512**

### CODE REVIEW

**Comment by roj1512** [comment]
@ije I didn’t update htm because the latest version wasn't allowing to change the color scheme for every blogState.

**Review by ije — APPROVED** [review]
LGTM！

**Review by lino-levan — APPROVED** [review]
LGTM

**Review by crowlKats — APPROVED** [review]
LGTM

**Pull request merged**
