### PR TITLE
Change address bar color on Mobile when using Dark Theme

### PR DESCRIPTION
**Pull request by Felipe-53**
It is pretty annoying having a light address bar on mobile when the website theme is dark. 

Just to make a point, compare these two:

1. Dark theme on mobile with light address bar 👎

image

2. Dark theme on mobile with dark address bar 👍

image

This PR sets a dark adress bar when in dark mode to address this issue.

It accomplishes this by usgin the `theme-color` meta tag. When in `dark` theme, it sets `theme-color` to `#000`, a reasonable default, I think.

Two tests were added and, of course, I tested manually on my phone.

When the `theme` setting is `"light"` or `"auto"` the  theme-color meta tag is simply not included, but this could be changed as well.

I guess there is some work to be done when the theme is set to "auto".

I know this project is minimalistic, so let me hear if this feature makes sense.

### CODE REVIEW

**Comment by Felipe-53** [comment]
Workflow failed because changed files were not properly fomatted. Fixed that in the last commit.

**Comment by Felipe-53** [comment]
I updated the first comment to better explain the PR. Let me know what you think.

**Comment by Felipe-53** [comment]
Any feedbacks? 🥲 I don't mind if the PR gets closed, haha. Just posted to get some feedback and, if found useful, contribute to the project. Thanks!

**Comment by lino-levan** [comment]
@hashrock PTAL! I'd love to get this merged for the `0.6.0` update.

**Review by hashrock — APPROVED** [review]
LGTM!

**Pull request merged**
