### PR TITLE
feat: add disable_html_sanitization frontmatter option

### LINKED ISSUE #108: toggle html sanitization
It would be nifty to be able to javascript Canvas API things from within markdown, imo.

many thanks,

### PR DESCRIPTION
**Pull request by lino-levan**
closes #108

### CODE REVIEW

**Comment by lino-levan** [comment]
@crowlKats please take a look!

**Review by crowlKats — APPROVED** [review]
LGTM

**Comment by crowlKats** [comment]
@lino-levan please format

**Comment by lino-levan** [comment]
That's embarrassing, will do.

**Pull request merged**
