### PR TITLE
feat: use import maps instead of ./deps and update to std@0.148.0

### PR DESCRIPTION
**Pull request by geoffreypetri**
Should be more convenient for future maintenance

### CODE REVIEW

**Comment by ije** [comment]
Since this is a shared module, we should avoid to use import maps

**Comment by geoffreypetri** [comment]
Hello @ije and thanks for your feedback.
I don't understand why should we avoid to use import maps in a shared module?

**Comment by ije** [comment]
because you need to point the import maps in deno.json or via `--import-map`, and you only can specify single import map currently. The best practice is using import maps with app build and deps.ts with modules.

**Comment by geoffreypetri** [comment]
Right, I didn't have this in mind, thank you.
Anyway, deno_blog isn't really a module. I think the impot_maps.json file should be created during the init.ts process.
Don't you agree ?

**Comment by roj1512** [comment]
Yes, it would be cool if is included in the template.

**Comment by ije** [comment]
create import maps is good, but the module itself should use `deps.ts`

**Pull request closed without merging**
